travis:
  secure:
    BINSTAR_TOKEN: JqJ/Wzv9uCfKkEeWGbkcszI3TAPO/K407n5qpBmOzXRTnBEwYtPpBv2B3xXLThT0Qm3940kvZM99fYU0uGmjEzuZhr6JDxv5ylZqmiehZxp2rsrrxxbfZDxbTa64EEPnV/MQbyjCltbVkIp+LUPifJC9UlXe4Q1xQyQTANzvJY2J24ZMWdRFWL7XT/dhuiBi2UwL27ENl+tCwjGdU0ohIN/NXLSqAt07kPSpE5W++ft2UoiOA14qg9CG+PJx+zZUZDXemzGlyw2xXF0tAep14+hn5XDOZNoparXcAnm+kAn61UZWOWMDUzbUZHUP3unVQxRKHA2mEBhwzFx/NtzMhzNEGzqg86SLxIn9VS7/Nz0FAfeZd/3gDOQ0xAmG44gsker6Rd0UaaF8QhZMDsrk6ymHVW/GBXIxPCYdmy0BDrB2pdSIB3oaPDEOQrr9C1v0ce9zBINLxTK+d8k68tsx+hAqnwU1aBjoAvE+agqHn4pQO4QGGkCFrfTJ8PXdWtV8VkfPLnLAK5AG/XqF1xhuwQNNzlvKHjoDJ62ayhkSs1lRMEp6BAJ3Z7yxI1JapgpPDu4P8+9g202fLXUvV7FWI8H1Fe61Di3tukuQE9P6ijl7+pucX7FxAvrjW29VIJlfjA0sNSv4TTtc5dsI0WUKe063ZFzxHoTNXn3D3MthQiE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
