travis:
  secure:
    BINSTAR_TOKEN: WiwzipstTc+M0pMzvj4+bLOMR+dRoEaA48iy3tuIFhzs5Ea9S37st7NfpGLTEjE9q/sTeIx3WV+nwdizjjLmAzwT2sz7E99J/VWm91NoBfB70khEaZN1x1KNFW6vP8iR5lGe7lnMLmVnpC1CVjQE2432UNKceOz5rPYHfWCOycJYxk+OysXhIF0l1DpOzCyxcY9VB2C+sAv90nbIHP8XTlTqPTamWUx+5xqLMcWzb3qX/zY1CmtTu7ACKXB3ORnfZGRb+YWoAL/L067V1rVPM+hMocH8yPMuMQd1jphT39ocym1KXZnTlsHQPV1yX1GdPGuIx6gXLyGicWHoE/ZLbbjNQI4AmRJ4IvoyyomAYJ+Jj+EAW2UZRMA5dyTeMwRS7bLiCz23zvwiciz0NLPMBrM3iDX1Ii49tvkLbLdqND1qgqCKqK/z5AS6i1RBuUr/htP9P4FYoWxEiQDl+wUQf9qlwhD/hJ4luFV1z0ngU3KU2GYp7lTAF2ApBXSfKfxMn3bv9zb6AC5RKk/XmtDVbx/edKngGxORZCXNIu2+HuTYlYZ+uzd1iPiPC4JlciUNJovz6TmEuecBFnX0PrhtucrZQTVwKMs7o86sUTFmZXj+KOgF4TCcuropgqL5tk+Da0CsfMUtQU5tECCEO5KBAgymLlDyrOTSILtGtvWD07A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
